[package]
name = "insertion_sort"
version = "0.1.0"
authors = ["15967-po2 <65965632+15967-po2@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
time = "0.2.26"